services:
  atrain:
    build: .
    image: jerome00253/atrain-web:latest
    container_name: atrain-web
    ports:
      - "8088:8088"
    volumes:
      - ./settings:/data/aTrain/settings
      - ./models_cache:/data/aTrain/models
      - ./transcriptions:/data/aTrain/transcriptions
      - ./custom_assets:/data/aTrain/custom_assets
    restart: unless-stopped
    environment:
      - XDG_DOCUMENTS_DIR=/data
      - PYTHONUNBUFFERED=1
